### ISSUE TITLE
Maybe Error in calculation of "chanSize" ?

### ISSUE THREAD

**Issue by vogtitec** [Rickgg/ESP-Dmx#6]
First of all: thanks for your great library!
I tested it and found it working fine for the first 31 dmx channels, but there was no output beyond 31... (although I initiated it with <dmxESPserial>.init(512) ).

A further look into the code revealed, that you calculate "chansize" as following:

``` C
    if (chanQuant < dmxMaxChannel || chanQuant <= 0) {
        chanQuant = defaultMax;
      }
      chanSize = chanQuant;
```

In this case, chanSize will always be set to defaultMax (which is 32), even if it is between 32 and 512.
So I think it should have been ">" instead of "<" to prevent entering numbers higher than dmxMacChannel:

``` C
    if (chanQuant > dmxMaxChannel || chanQuant <= 0) {
        chanQuant = dmxMaxChannel;
    }
```

I will test it with these changes on transmitting more than 32 channels and report later...

**Comment by Rickgg** [comment]
Excellent! Thanks. Do a PR if it works :)

**Comment by vogtitec** [comment]
Tested it and everything works as expected! Thanks for merging it in your code!
